### ISSUE TITLE
[Windows] Crashes with no stacktrace

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-taskpools#2]
The DFS and heat benchmarks are crashing with no stacktrace on Windows: https://github.com/status-im/nim-taskpools/runs/2962435403#step:13:89

```
========================================================================================
Running [ c  ] benchmarks/heat/taskpool_heat.nim
========================================================================================
[NimScript] exec: nim c  --verbosity:0 --hints:off --warnings:off --threads:on -d:release --stacktrace:on --linetrace:on --outdir:build -r benchmarks/heat/taskpool_heat.nim
Error: execution of an external program failed: 'D:\a\nim-taskpools\nim-taskpools\nim-taskpools\build\taskpool_heat.exe '
stack trace: (most recent call last)
C:\Users\RUNNER~1\AppData\Local\Temp\nimblecache-0\nimscriptapi_2697630897.nim(187, 16)
D:\a\nim-taskpools\nim-taskpools\nim-taskpools\taskpools.nimble(37, 8) testTask
D:\a\nim-taskpools\nim-taskpools\nim-taskpools\taskpools.nimble(26, 8) test
D:\a\nim-taskpools\nim-taskpools\nim\lib\system\nimscript.nim(260, 7) exec
D:\a\nim-taskpools\nim-taskpools\nim\lib\system\nimscript.nim(260, 7) Error: unhandled exception: FAILED: nim c  --verbosity:0 --hints:off --warnings:off --threads:on -d:release --stacktrace:on --linetrace:on --outdir:build -r benchmarks/heat/taskpool_heat.nim [OSError]
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Exception raised during nimble script execution
Error: Process completed with exit code 1.
```

Looking locally with gdb we get this

```
Thread 36 received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 5752.0x24d8]
0x00007ffde2608c07 in ntdll!RtlpNtMakeTemporaryKey () from C:\windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffde2608c07 in ntdll!RtlpNtMakeTemporaryKey () from C:\windows\SYSTEM32\ntdll.dll
#1  0x00007ffde25f5c85 in ntdll!RtlZeroHeap () from C:\windows\SYSTEM32\ntdll.dll
#2  0x00007ffde25c49db in ntdll!memset () from C:\windows\SYSTEM32\ntdll.dll
#3  0x00007ffde2607a94 in ntdll!RtlpNtMakeTemporaryKey () from C:\windows\SYSTEM32\ntdll.dll
#4  0x00007ffde25aba02 in ntdll!memset () from C:\windows\SYSTEM32\ntdll.dll
#5  0x00007ffde250eb2e in ntdll!RtlFreeHeap () from C:\windows\SYSTEM32\ntdll.dll
#6  0x00007ffde08d9d0c in msvcrt!free () from C:\windows\System32\msvcrt.dll
#7  0x000000000042b8d2 in cleanup__SHKET3vaU9a9cCo73MoYsGXgflowvars (fv=...) at [...]/nim-taskpools/taskpools/flowvars.nim:41
#8  sync__wTuc87TnWJbDfXB9bbnSyFgflowvars (fv=...) at [...]/nim-taskpools/taskpools/flowvars.nim:72
#9  heat__RQB9b6xKuruBDMMs9apUS0MA (m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>,
    il@entry=3582, iu=<optimized out>, iu@entry=0) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:144
#10 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3580,
    iu=<optimized out>, iu@entry=0) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#11 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3576,
    iu=<optimized out>, iu@entry=0) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#12 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3568,
    iu=<optimized out>, iu@entry=0) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#13 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3552,
    iu=<optimized out>, iu@entry=0) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#14 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3520,
    iu=<optimized out>, iu@entry=0) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#15 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3456,
    iu=<optimized out>, iu@entry=0) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#16 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3328,
    iu=<optimized out>, iu@entry=176570576) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#17 0x000000000042b760 in heat__RQB9b6xKuruBDMMs9apUS0MA (
    m=<error reading variable: Cannot access memory at address 0x2b1578c7c5620000>, il=<optimized out>, il@entry=3072,
    iu=<optimized out>, iu@entry=3584) at [...]/nim-taskpools/benchmarks/heat/taskpool_heat.nim:143
#18 0x000000000042db4e in taskpool_heat__U5YlCX8Yrr5EIVO1DlnNSQ (m=..., il=3072, iu=3584, fut=...)
    at [...]/nim-taskpools/taskpools/taskpools.nim:497
#19 0x000000000042e376 in taskpool_heat__5BGkgO9b76lIYZk7e9ccCl9cg (argsX60gensym17100250_=0xb251a50)
    at [...]/nim-taskpools/taskpools/shims_pre_1_6/tasks.nim:130
#20 0x0000000000425a08 in invoke__h7ET9aV09bIhD9aJ85VPycUJQtasks (task=...)
```

**Comment by mratsim** [comment]
Address sanitizer commands so it's not lost

````bash
nim c -r --cc:clang --passC:"-fsanitize=address" --passL:"-L/d/Apps/LLVM/lib/clang/9.0.0/lib/windows -fsanitize=address -lclang_rt.asan_
dynamic-x86_64" --debugger:native --verbosity:0 --hints:off --warnings:off --threads:on --stacktrace:on --linetrace:on --outdir:build benchmarks/heat/taskpool_heat.nim
``
